Home_work 3
makarovNick/made_2019_algorithm pull request #1
Opened 2019-11-01 21:29 UTC by makarovNick

6_1. Обход дерева в порядке pre-order
https://contest.yandex.ru/contest/14885/run-report/23338262/

7_1. Солдаты ДД
https://contest.yandex.ru/contest/14885/run-report/23444486/

2019-11-01 22:22 UTC, ylyubimov approved these changes

2019-11-01 22:24 UTC, ylyubimov requested changes

2019-11-01 22:24 UTC, ylyubimov commented on treap.cpp
> +		int size();
const

2019-11-01 22:24 UTC, ylyubimov commented on treap.cpp
> +		int sizeOfLeft()
Кажется в метод это не нужно выносить

2019-11-01 22:24 UTC, ylyubimov commented on treap.cpp
> +		int size();
Этот метод в сущности можно убрать

2019-11-01 22:24 UTC, ylyubimov commented on treap.cpp
> +	public:
У struct'уры не надо писать public

2019-11-01 22:30 UTC, ylyubimov requested changes
Давай задачи по отдельности присылать, так будет удобнее

2019-11-01 22:30 UTC, ylyubimov commented on treap.cpp
> +	bool contains(T val);
const

2019-11-01 22:30 UTC, ylyubimov commented on treap.cpp
> +	bool insert(T val);
Во всех функциях T -> T& или const T&

2019-11-01 22:30 UTC, ylyubimov commented on treap.cpp
> +	int size()
const

2019-11-01 22:30 UTC, ylyubimov commented on treap.cpp
> +	node* _insert(node* curNode, T val);
Пока по стеку вызовов пройдешь, сколько раз val скопируешь? Давай использовать ссылку)

2019-11-01 22:30 UTC, ylyubimov commented on treap.cpp
> +	if (_find(root, value, keyPos) != nullptr)
лучше прямо это и возвращай

2019-11-01 22:30 UTC, ylyubimov commented on treap.cpp
> +			curNode = rotateRight(curNode);
Как-то это не похоже на Splay дерево. В нем поворотов нет.

2019-11-02 13:44 UTC, makarovNick commented on treap.cpp
> +			curNode = rotateRight(curNode);
> Как-то это не похоже на Splay дерево. В нем поворотов нет.

У меня задание про декартово, но я без отдельного split / merge . Просто, как в АВЛ, поворачиваю.

2019-11-09 00:24 UTC, ylyubimov commented on treap.cpp
> +			curNode = rotateRight(curNode);
Ну ведь тогда, это не декартово, его нельзя так поворачивать)

2019-11-11 15:26 UTC, closed without merging