Задача 18. Построение выпуклой оболочки
makarovNick/made_2019_algorithm pull request #12
Opened 2019-12-18 16:52 UTC by makarovNick

Вариант 1. С помощью алгоритма Грэхема.
https://contest.yandex.ru/contest/16362/run-report/29061223/

2019-12-29 20:59 UTC, ylyubimov requested changes
В целом ок. Пока 4 балла. Исправь мелочь

2019-12-29 20:59 UTC, ylyubimov commented on convex_hull.cpp
> +    bool operator<(const Point& p) const
Кажется сравнение точек может быть какое угодно. Это не самое очевидное. Не стоит делать его методом сравнения.

2019-12-29 20:59 UTC, ylyubimov commented on convex_hull.cpp
> +std::vector<Point> convexHull(std::vector<Point> points)
вектор копируется. Зачем?

2019-12-30 14:04 UTC, makarovNick commented on convex_hull.cpp
> +    bool operator<(const Point& p) const
перенес в компаратор сортировки

2019-12-30 14:04 UTC, makarovNick commented on convex_hull.cpp
> +std::vector<Point> convexHull(std::vector<Point> points)
ну я же его сортирую

2020-01-07 10:24 UTC, ylyubimov commented on convex_hull.cpp
> +std::vector<Point> convexHull(std::vector<Point> points)
хорошо

2020-01-07 10:25 UTC, ylyubimov approved these changes

2020-01-14 03:49 UTC, merged