Create quadratic_probing_hash.cpp
makarovNick/made_2019_algorithm pull request #2
Opened 2019-11-11 15:16 UTC by makarovNick

8. Хеш-таблица
1_1. Для разрешения коллизий используйте квадратичное пробирование. i-ая проба
g(k, i)=g(k, i-1) + i (mod m). m - степень двойки.

https://contest.yandex.ru/contest/15369/run-report/24078921/

2019-11-13 22:07 UTC, ylyubimov requested changes

2019-11-13 22:07 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +class HashTable
Раз ты у нас впереди планеты всей. То давай сделаем хэш-таблицу шаблонной. Добавим возможность также инициализировать ее функцией считающей хэш.

2019-11-13 22:07 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +	~HashTable();
Правило пяти

2019-11-13 22:07 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +	bool Insert(const std::string& key);
Сделай метод Insert(T&& key) также

2019-11-13 22:07 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +		bool deleted;
Давай лучше не будем дополнительный флаг в каждой ячейке хранить, а сделаем чтобы значение для deleted пользователь передевал снаружи.
Спец. строки "__DELETED__", например. Аналогично для пустых строк. Вдруг я захочу пустую строчку в HashTable упаковать?

2019-11-13 22:07 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +		table[i] = nullptr;
Можно кстати указателем на специальный узел __DELETED__ можно сделать одним, а все указатели на него перекинуть)

2019-11-13 22:07 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +		if (table[_hash] == nullptr)
Давай не будем по таблице бегать дважды. Сделаем за один проход, без предварительно вызова Has?

2019-11-13 22:07 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +	while (i < capacity)
И здесь тоже

2019-11-13 22:07 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +				Insert(tmp[i]->data);
Нужно переподвесить этот узел в правильное место, а не переаллоцировать его)

2019-11-17 18:47 UTC, makarovNick commented
Все исправил и добавил шаблоны и хэш.

2019-11-21 22:45 UTC, ylyubimov requested changes

2019-11-21 22:45 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +	const std::string deleted = "!@#$%^__DELETED_^%$#@!";
Вот тут я имел ввиду, что можно разрешить переопределять эту константу в конструкторе.

2019-11-21 22:45 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +		if (table[_hash]->data.compare(deleted) && table[_hash]->data.compare(key) == 0)
Вот этой строчки не понял, можешь пояснить?

2019-11-21 22:45 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +				Insert(tmp[i]->data);
Этот комментарий еще актуальный

2019-11-21 22:45 UTC, ylyubimov commented on quadratic_probing_hash.cpp
> +		if (table[_hash]->data.compare(deleted) && table[_hash]->data.compare(key) == 0)
И вообще я тебя обманул. Метод Insert не получится сделать не дойдя до конца. Но нужно сделать это только один раз. Запомнив место вставки нового элемента

2019-11-22 20:13 UTC, makarovNick commented on quadratic_probing_hash.cpp
> +		if (table[_hash]->data.compare(deleted) && table[_hash]->data.compare(key) == 0)
> Вот этой строчки не понял, можешь пояснить?

Если оказалось, что такой элемент уже в таблице. 

А первое условие - не знаю)), уберу. Неудачная проверка на то, что захотели вставить зарезервированный ключ

2019-11-26 23:06 UTC, ylyubimov approved these changes

2019-11-27 20:40 UTC, merged