fixed
makarovNick/made_2019_algorithm pull request #3
Opened 2019-11-13 20:37 UTC by makarovNick

6_1. Обход дерева в порядке pre-order

https://contest.yandex.ru/contest/14885/run-report/23338262/

7_1. Солдаты ДД

https://contest.yandex.ru/contest/14885/run-report/23444486/

2019-11-17 18:24 UTC, ylyubimov requested changes

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	~Treap()
Правило пяти

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +		~Node()
Правило пяти)

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	Node* merge(Node* l, Node* r);
не экономь на буквах)

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	Node* _find(Node* curNode, const T& val, int& keyPos);
скорее всего метод должен быть const

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	T FindByPosition(int keyPos);
const?

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	bool Contains(const T& val);
const должен быть

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	T FindByPosition(Node* curNode, int keyPos);
const

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +		right_size = (right != nullptr) ? right->tree_size : 0;
Не надо так, в новой строчки, с честным объявлением

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	Node* y;
Почему такие разные называния?

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	if (x->left != nullptr && x->left->priority > x->priority)
Как может быть так? Почему приоритет дочернего узла больше текущего?

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	if (x->left != nullptr && x->left->priority > x->priority)
Почему алгоритм склейки не зависит от T2?

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +bool Treap<T>::Contains(const T& value)
метод const

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +inline int Treap<T>::GetPosition(const T& value)
const

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	curNode = merge(splitted.first, splitted.second);
Зачем ты разбил и склеил обратно?

2019-11-17 18:24 UTC, ylyubimov commented on cartesian_tree_soldiers.cpp
> +	splitted = split(curNode);
auto splitted = split(curNode);

2019-11-17 18:24 UTC, ylyubimov commented on pre_order_traversal.cpp
> +		y = newnode;
При каких условиях сработает этот if? Что за подзадача?

2019-11-17 18:24 UTC, ylyubimov commented on pre_order_traversal.cpp
> +	tr.preOrderTraversal([](const int v) {std::cout << v << " "; });
Утечка памяти, память нигде не освобождается. Вообще - это -1 балл, по нашим минимальным требованиям

2019-11-18 16:13 UTC, makarovNick commented on cartesian_tree_soldiers.cpp
> +	curNode = merge(splitted.first, splitted.second);
> Зачем ты разбил и склеил обратно?

Сначала я рекурсивно спускаюсь туда, где должна будет стоять нода.
Затем спличу по ней и получай пару, между которыми она должна стоять.
Merge возвращают уже нужную позицию, соединив те вершины.

2019-11-18 16:14 UTC, makarovNick commented on pre_order_traversal.cpp
> +		y = newnode;
> При каких условиях сработает этот if? Что за подзадача?

VS подсвечивал, что может быть nullptr. А ведь, дейтсвительно, не может

2019-11-18 16:14 UTC, makarovNick commented on pre_order_traversal.cpp
> +	tr.preOrderTraversal([](const int v) {std::cout << v << " "; });
> Утечка памяти, память нигде не освобождается. Вообще - это -1 балл, по нашим минимальным требованиям

Упс, просто не конечную версию скинул

2019-12-05 01:01 UTC, ylyubimov approved these changes

2019-12-05 08:50 UTC, merged